### ISSUE TITLE
Create a Fight-Scene Content Model

### ISSUE THREAD

**Issue by BenedictHomuth** [derechtenap/xeon-eoh#17]
In order to make the game more unique every level should has its own style. (Enemys, Difficulty, "Dungeon"). 

We need a way to store all those information to dynamically load this content onto the webpage.

**Vision No. 1:** 

- General Idea:
    Make it a JSON-Object which itself can maybe be stored in a document-oriented database.
		
    Depending on which "level" the user clicked, load the specific object (--> POST-Arguments)
- What we need to store:
Enemys: 
Health, Attack-Damage, Drops (or a drop table), XP, Sprites (per enemy)
	

	World-Info:
Which background should be displayed.
How many dungeons are there in this specific level.
Did the user already played or beat the level. (Needed?)

**Comment by timderes** [comment]
> Enemys:
Health, Attack-Damage, Drops (or a drop table), XP, Sprites (per enemy)

I like the system which was used in _The Elder Scrolls V: Skyrim_. They used different variants of enemies:
- Bandit
- Bandit Outlaw
- Bandit Thug

Each tier could use some different attacks.

> Did the user already played or beat the level. (Needed?)

It would allow the player to grind items. This has advantages and disadvantages...

**Comment by timderes** [comment]
> World-Info:
Which background should be displayed.

We can display backgrounds with `background-image: url(...)` (red striped zone). I suggest making the` background-position: relative`. So we can position our enemies for every background differently (orange dotted zone).
![image](https://user-images.githubusercontent.com/50623315/97642379-42294a80-1a45-11eb-8b75-3cb45cb92ecd.png)

**Comment by timderes** [comment]
> World-Info:
Which background should be displayed.
How many dungeons are there in this specific level.
Did the user already played or beat the level. (Needed?)


### **First idea:**
**forest.json**
```json
{
    "level_name": "Forest",
    "level_desc": "Dark Forest very spooky",
    "dungeon_count": 10,
    "dungeon_names": [],
    "rewards": [],
    "background_image": "./frontend/img/background.jpg",
    "spawnable_enemies": [
        "Bandit",
        "Knight"
    ]
}
```

**Comment by BenedictHomuth** [comment]
Trying to implement it as described above for now.

**Comment by timderes** [comment]
**Asset Path**
https://github.com/derechtenap/xeon-eoh/blob/5547b47cfb73351cbd1a88dec35d2c7b77127cec/frontend/js/fight.js#L1
https://github.com/derechtenap/xeon-eoh/blob/5547b47cfb73351cbd1a88dec35d2c7b77127cec/frontend/js/fight.js#L2
Maybe we should use a relative path for this 🤔

**Comment by BenedictHomuth** [comment]
> Maybe we should use a relative path for this 🤔

Done.
