### ISSUE TITLE
How To Store The Enemy Data?

### ISSUE THREAD

**Issue by timderes** [derechtenap/xeon-eoh#18]
### **1. Which file format should we use?**
There are many possible options. Like XML or JSON. I personally would prefer JSON over XML. Since the syntax is pretty straight forward and it works with JavaScript. Are there any other good formats (Maybe YML)?

### **2. How to store the data?**
As I mentioned in #17, I like the System which is used in _The Elder Scrolls V: Skyrim_. It used one base unit and adds some stronger variants trough the story and level progress. 

**I created a small example file (bandit.json), which stores two different bandit variants:**
```json
{
    "id": 1,
    "activ": false,
    "enemy": {
        "tier_one": {
            "name": "Bandit",
            "base_attack": 5,
            "base_hp": 100,
            "xp": 10,
            "weapon_pool": [
                "sword",
                "bow"
            ],
            "drop_pool": {
                "gold": {
                    "item_id": 1,
                    "percantage": 90,
                    "min_amount": 1,
                    "max_amount": 5
                }
            },
            "image": "<url>"
        },
        "tier_two": {
            "name": "<tier_two_name>",
            "base_attack": 7,
            "base_hp": 120,
            "xp": 15,
            "weapon_pool": [
                "sword",
                "bow"
            ],
            "drop_pool": {
                "gold": {
                    "item_id": 1,
                    "percantage": 90,
                    "min_amount": 1,
                    "max_amount": 5
                }
            },
            "image": "<url>"
        }
    }
}
```

**Comment by BenedictHomuth** [comment]
**1.  Which file format should we use?**
There are a lot of alternatives out there to choose from, but I would also suggest to stick to JSON, since most of my experience with this kind of data storage lies there.

**2.  How to store the data?**
The system from TES-V sounds great and gives a good opportunity to generate a lot of content fairly quick. Your outlined approach of structuring this data also looks sophisticated. 

A little bit of refactoring might be needed in my opinion.

- I would like to see a change in how we "reference" to our tier-system. I think it would be easier to have all our "tiers" in an array  instead of an object, so we can use the index of this array as our "tier number".  (Starting from 0 then obviously)

Can you furthermore give a little bit of information on what the key "activ" means and which purpose it has?

**Comment by timderes** [comment]
> Can you furthermore give a little bit of information on what the key "activ" means and which purpose it has?

Ah, I forgot to explain this. Basically, it is a true or false value to indicate a unit which should spawn within the game. If the value is set to `false` it is unable to be spawned. I can be used for debugging or for placeholder units. Also to remove units from the game. For example, if they are too strong...

> A little bit of refactoring might be needed in my opinion.

Yeah, that's right. I think this approach should be better: 😄
```json
 "tier": [
               {
                       "name": "Bandit",
                       "base_attack": 5
                       ...
               },
              { ... }
]
```
Did I miss any variables? Which one would you add to the Unit JSON? @BenedictHomuth

**Comment by BenedictHomuth** [comment]
> Ah, I forgot to explain this. Basically, it is a true or false value to indicate a unit which should spawn within the game. If the value is set to false it is unable to be spawned. I can be used for debugging or for placeholder units. Also to remove units from the game. For example, if they are too strong...

Sounds good especially for debugging.

I sketched the JSON-File for the time being like this:
```json {
    "id": 1,
    "activ": false,
    "tier": [
        {
                "name": "Bandit",
                "base_attack": 5,
                "base_hp": 100,
                "xp": 10,
                "weapon_pool": [
                    "sword",
                    "bow"
                ],
                "drop_pool": {
                    "gold": {
                        "item_id": 1,
                        "percantage": 90,
                        "min_amount": 1,
                        "max_amount": 5
                    }
                },
                "image": "../frontend/img/bandit.svg"
        }
    ]
}
```

> Did I miss any variables? Which one would you add to the Unit JSON? @BenedictHomuth

I would say no for now, since it would be to complex for initial testing otherwise.
